version: "2"
services:
  mongo0:
    hostname: mongo0
    container_name: mongo0
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo1:
    hostname: mongo1
    container_name: mongo1
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  mongo2:
    hostname: mongo2
    container_name: mongo2
    image: mongo
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]

    
  mongoconfigure:
    hostname: mongoconfigure
    container_name: mongoconfigure
    image: mongo
    volumes:
       - ./scripts:/scripts
    entrypoint: [ "/scripts/setup.sh" ]
